name: flutter_keepscreenon
description: A package can help you to keep the device's screen on programmatically without any permission.
version: 0.1.1
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_keepscreenon

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.fuyumi.flutterkeepscreenon
    pluginClass: FlutterKeepscreenonPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"