name: flutter_keepscreenon
description: A package can help you to prevent your flutter app's screen going to sleep programmatically.
version: 0.0.2
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_keepscreenon

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.fuyumi.flutterkeepscreenon
    pluginClass: FlutterKeepscreenonPlugin

environment:
    sdk: ">=1.8.0 <2.0.0"
